---
title: "championship.Rmd"
author: "Jackson Roe"
date: '2022-07-04'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(dplyr)
library(ggthemes)
```

```{r}
mm_data <- read_csv(file = "data_cleaned.csv")

# 2022 data

last_year <- tribble(~WSEED, ~times_won,
        1, 1)

# filter data

data <- mm_data |>
  filter(ROUND == 6) |>
  group_by(WSEED) |>
  summarize(times_won = sum(WSEED) / WSEED)

# join to 2022 data

combined <- full_join(data, last_year)

# above command did not add in the row, it kept it separate. Now combining the rows

combined |> 
  group_by(WSEED) |> 
  summarize(times_won = sum(WSEED) / WSEED)

# Rows are still repeating, I have 24 rows where WSEED = 1, and so forth. Making a tibble to fix this.

joined_data <- tribble(~WSEED, ~times_won, 
        1, 24,
        2, 5,
        3, 4,
        4, 1,
        6, 1,
        7, 1,
        8, 1)

# graphing

joined_data |> 
  ggplot(aes(x = WSEED, y = times_won / 37)) + 
    geom_col(color = "honeydew4", fill = "honeydew3") + 
    scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8)) +
  scale_y_continuous(labels = scales::percent_format()) + 
  theme_bw() + 
  labs(title = "Percent Chance of Each Seed Winning the National Championship", 
       subtitle = "It is very likely a 1 seed will win, and no 5 seed has ever won", 
       x = "Seed", 
       y = "Percent Chance of Winning",
       caption = "Source: kaggle (Woody Gilbertson; 2021)")


  
```

